#ifndef servicesDef_h
#define servicesDef_h

#define RESTART_MSG     7
#define WHOAMI_MSG      9
#define BLINKME_MSG     10
#define IMUSENDINIT_MSG 1
#define OPENLOOPFESUPDATE_MSG 2
#define STOPOPENLOOPFES_MSG 8
#define CLOSEDLOOPFESCONTROL_MSG 3
#define CLOSEDLOOPFESREFERENCEUPDATE_MSG 4
#define PIDSPARAMETERSUPDATE_MSG 5
#define MP_PIDSPARAMETERSUPDATE_MSG 13
#define MP_PIDSFESREFERENCEUPDATE_MSG 14
#define MP_PIDSTWODOFLIMBFES_MSG 15
#define _MSG
#define _MSG

#endif